name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Assembly Version
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "[0-9]+\\.[0-9]+\\</AssemblyVersion\\>"
        replace: ${{ github.run_number }}.0</AssemblyVersion>
    - name: Update File Version
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "[0-9]+\\.[0-9]+\\</FileVersion\\>"
        replace: ${{ github.run_number }}.0</FileVersion>
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./src
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./src
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: source
        path: src
